name: redteaspoon
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9421775282826275
  lightness: 0.5121221817098558
  saturation: 0.7012910435441881
  rhythmicContrast: 0.195615271339193
purpose: []
